export type CultureCat = "capitales" | "villes" | "depts" | "rois" | "presidents" | "guerres";
export type CultureQ = { q: string; a: string; opts: [string, string, string]; cat: CultureCat };

export const CAT_LABELS: Record<CultureCat, string> = {
  capitales: "Capitales du monde",
  villes: "Villes de France",
  depts: "Départements",
  rois: "Rois & Reines",
  presidents: "Présidents",
  guerres: "Grandes guerres",
};

export const CULTURE: CultureQ[] = [
  // ── CAPITALES ──────────────────────────────────────────────────
  { q: "Quelle est la capitale de l'Allemagne ?", a: "Berlin", opts: ["Paris", "Munich", "Hambourg"], cat: "capitales" },
  { q: "Quelle est la capitale du Japon ?", a: "Tokyo", opts: ["Osaka", "Kyoto", "Hiroshima"], cat: "capitales" },
  { q: "Quelle est la capitale du Brésil ?", a: "Brasília", opts: ["Rio de Janeiro", "São Paulo", "Salvador"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Australie ?", a: "Canberra", opts: ["Sydney", "Melbourne", "Brisbane"], cat: "capitales" },
  { q: "Quelle est la capitale du Canada ?", a: "Ottawa", opts: ["Toronto", "Montréal", "Vancouver"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Argentine ?", a: "Buenos Aires", opts: ["Santiago", "Lima", "Bogotá"], cat: "capitales" },
  { q: "Quelle est la capitale de la Russie ?", a: "Moscou", opts: ["Saint-Pétersbourg", "Novossibirsk", "Kazan"], cat: "capitales" },
  { q: "Quelle est la capitale de la Chine ?", a: "Pékin", opts: ["Shanghai", "Hong Kong", "Canton"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Inde ?", a: "New Delhi", opts: ["Mumbai", "Calcutta", "Chennai"], cat: "capitales" },
  { q: "Quelle est la capitale des États-Unis ?", a: "Washington D.C.", opts: ["New York", "Los Angeles", "Chicago"], cat: "capitales" },
  { q: "Quelle est la capitale du Mexique ?", a: "Mexico", opts: ["Guadalajara", "Cancún", "Monterrey"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Espagne ?", a: "Madrid", opts: ["Barcelone", "Séville", "Valence"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Italie ?", a: "Rome", opts: ["Milan", "Naples", "Turin"], cat: "capitales" },
  { q: "Quelle est la capitale du Portugal ?", a: "Lisbonne", opts: ["Porto", "Faro", "Coimbra"], cat: "capitales" },
  { q: "Quelle est la capitale des Pays-Bas ?", a: "Amsterdam", opts: ["Rotterdam", "La Haye", "Utrecht"], cat: "capitales" },
  { q: "Quelle est la capitale de la Belgique ?", a: "Bruxelles", opts: ["Anvers", "Liège", "Gand"], cat: "capitales" },
  { q: "Quelle est la capitale de la Suisse ?", a: "Berne", opts: ["Zurich", "Genève", "Lausanne"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Autriche ?", a: "Vienne", opts: ["Salzbourg", "Graz", "Innsbruck"], cat: "capitales" },
  { q: "Quelle est la capitale de la Grèce ?", a: "Athènes", opts: ["Thessalonique", "Héraklion", "Patras"], cat: "capitales" },
  { q: "Quelle est la capitale de la Turquie ?", a: "Ankara", opts: ["Istanbul", "Izmir", "Bursa"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Égypte ?", a: "Le Caire", opts: ["Alexandrie", "Louxor", "Assouan"], cat: "capitales" },
  { q: "Quelle est la capitale du Maroc ?", a: "Rabat", opts: ["Casablanca", "Marrakech", "Fès"], cat: "capitales" },
  { q: "Quelle est la capitale du Nigeria ?", a: "Abuja", opts: ["Lagos", "Kano", "Ibadan"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Afrique du Sud ?", a: "Pretoria", opts: ["Le Cap", "Johannesburg", "Durban"], cat: "capitales" },
  { q: "Quelle est la capitale du Kenya ?", a: "Nairobi", opts: ["Mombasa", "Kisumu", "Nakuru"], cat: "capitales" },
  { q: "Quelle est la capitale de la Pologne ?", a: "Varsovie", opts: ["Cracovie", "Gdańsk", "Wrocław"], cat: "capitales" },
  { q: "Quelle est la capitale de la Suède ?", a: "Stockholm", opts: ["Göteborg", "Malmö", "Uppsala"], cat: "capitales" },
  { q: "Quelle est la capitale de la Norvège ?", a: "Oslo", opts: ["Bergen", "Trondheim", "Stavanger"], cat: "capitales" },
  { q: "Quelle est la capitale du Danemark ?", a: "Copenhague", opts: ["Aarhus", "Odense", "Aalborg"], cat: "capitales" },
  { q: "Quelle est la capitale de la Finlande ?", a: "Helsinki", opts: ["Tampere", "Turku", "Oulu"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Irlande ?", a: "Dublin", opts: ["Cork", "Galway", "Limerick"], cat: "capitales" },
  { q: "Quelle est la capitale de la Hongrie ?", a: "Budapest", opts: ["Debrecen", "Miskolc", "Pécs"], cat: "capitales" },
  { q: "Quelle est la capitale de la République tchèque ?", a: "Prague", opts: ["Brno", "Ostrava", "Plzeň"], cat: "capitales" },
  { q: "Quelle est la capitale de la Roumanie ?", a: "Bucarest", opts: ["Cluj-Napoca", "Timișoara", "Iași"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Ukraine ?", a: "Kiev", opts: ["Kharkiv", "Odessa", "Lviv"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Iran ?", a: "Téhéran", opts: ["Ispahan", "Chiraz", "Tabriz"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Arabie Saoudite ?", a: "Riyad", opts: ["Djeddah", "La Mecque", "Médine"], cat: "capitales" },
  { q: "Quelle est la capitale de la Thaïlande ?", a: "Bangkok", opts: ["Chiang Mai", "Pattaya", "Phuket"], cat: "capitales" },
  { q: "Quelle est la capitale du Vietnam ?", a: "Hanoï", opts: ["Hô Chi Minh-Ville", "Da Nang", "Hué"], cat: "capitales" },
  { q: "Quelle est la capitale de la Corée du Sud ?", a: "Séoul", opts: ["Busan", "Incheon", "Daegu"], cat: "capitales" },
  { q: "Quelle est la capitale du Pakistan ?", a: "Islamabad", opts: ["Karachi", "Lahore", "Rawalpindi"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Éthiopie ?", a: "Addis-Abeba", opts: ["Dire Dawa", "Gondar", "Mekele"], cat: "capitales" },
  { q: "Quelle est la capitale de l'Algérie ?", a: "Alger", opts: ["Oran", "Constantine", "Annaba"], cat: "capitales" },
  { q: "Quelle est la capitale de la Tunisie ?", a: "Tunis", opts: ["Sfax", "Sousse", "Kairouan"], cat: "capitales" },
  { q: "Quelle est la capitale du Sénégal ?", a: "Dakar", opts: ["Saint-Louis", "Thiès", "Ziguinchor"], cat: "capitales" },
  { q: "Quelle est la capitale de la Colombie ?", a: "Bogotá", opts: ["Medellín", "Cali", "Cartagène"], cat: "capitales" },
  { q: "Quelle est la capitale du Pérou ?", a: "Lima", opts: ["Cusco", "Arequipa", "Trujillo"], cat: "capitales" },
  { q: "Quelle est la capitale de Cuba ?", a: "La Havane", opts: ["Santiago de Cuba", "Camagüey", "Holguín"], cat: "capitales" },

  // ── VILLES DE FRANCE ───────────────────────────────────────────
  { q: "Quelle ville française est surnommée « la Ville Rose » ?", a: "Toulouse", opts: ["Bordeaux", "Lyon", "Montpellier"], cat: "villes" },
  { q: "Quelle est la 2e ville de France par la population ?", a: "Marseille", opts: ["Lyon", "Bordeaux", "Toulouse"], cat: "villes" },
  { q: "Dans quelle ville se tient le festival de cinéma le plus célèbre ?", a: "Cannes", opts: ["Nice", "Deauville", "Biarritz"], cat: "villes" },
  { q: "Dans quelle ville se trouve le Parlement européen (siège officiel) ?", a: "Strasbourg", opts: ["Bruxelles", "Luxembourg", "Paris"], cat: "villes" },
  { q: "Dans quelle ville se trouve le château des Ducs de Bretagne ?", a: "Nantes", opts: ["Rennes", "Brest", "Quimper"], cat: "villes" },
  { q: "Quelle ville est réputée pour son festival international de BD ?", a: "Angoulême", opts: ["Bordeaux", "Nîmes", "Tours"], cat: "villes" },
  { q: "Dans quelle ville est née Jeanne d'Arc ?", a: "Domrémy-la-Pucelle", opts: ["Orléans", "Reims", "Rouen"], cat: "villes" },
  { q: "Dans quelle ville Jeanne d'Arc fut-elle brûlée vive ?", a: "Rouen", opts: ["Orléans", "Paris", "Amiens"], cat: "villes" },
  { q: "Quelle ville est surnommée « capitale mondiale de la gastronomie » ?", a: "Lyon", opts: ["Paris", "Bordeaux", "Strasbourg"], cat: "villes" },
  { q: "Dans quelle ville se trouve le palais des Papes ?", a: "Avignon", opts: ["Montpellier", "Nîmes", "Arles"], cat: "villes" },
  { q: "Quelle ville est connue pour sa porcelaine ?", a: "Limoges", opts: ["Sèvres", "Nevers", "Quimper"], cat: "villes" },
  { q: "Quelle ville alsacienne est surnommée « Petite Venise » ?", a: "Colmar", opts: ["Strasbourg", "Mulhouse", "Sélestat"], cat: "villes" },
  { q: "Quelle ville est connue pour son industrie du parfum ?", a: "Grasse", opts: ["Nice", "Cannes", "Antibes"], cat: "villes" },
  { q: "Dans quelle ville est née Victor Hugo ?", a: "Besançon", opts: ["Paris", "Nancy", "Rouen"], cat: "villes" },
  { q: "Quelle ville est connue pour ses madeleines ?", a: "Commercy", opts: ["Nancy", "Metz", "Bar-le-Duc"], cat: "villes" },
  { q: "Dans quelle ville se trouve le mémorial pour la paix ?", a: "Caen", opts: ["Bayeux", "Rouen", "Cherbourg"], cat: "villes" },
  { q: "Dans quelle ville est enterré Napoléon Bonaparte ?", a: "Paris", opts: ["Ajaccio", "Fontainebleau", "Brienne-le-Château"], cat: "villes" },
  { q: "Dans quelle ville se trouve le Capitole, hôtel de ville célèbre ?", a: "Toulouse", opts: ["Bordeaux", "Montpellier", "Nîmes"], cat: "villes" },
  { q: "Dans quelle ville se trouve la préfecture de la Côte-d'Or ?", a: "Dijon", opts: ["Beaune", "Mâcon", "Chalon-sur-Saône"], cat: "villes" },
  { q: "Quelle ville est connue pour le miroir d'eau et la place de la Bourse ?", a: "Bordeaux", opts: ["Toulouse", "Nantes", "Lyon"], cat: "villes" },
  { q: "Quelle est la préfecture du Finistère ?", a: "Quimper", opts: ["Brest", "Morlaix", "Lorient"], cat: "villes" },
  { q: "Quelle ville française abrite un célèbre festival de jazz en Gascogne ?", a: "Marciac", opts: ["Nice", "Toulouse", "Montpellier"], cat: "villes" },
  { q: "Dans quelle ville se trouve le château de Versailles ?", a: "Versailles", opts: ["Saint-Germain-en-Laye", "Fontainebleau", "Rambouillet"], cat: "villes" },
  { q: "Quelle ville est le siège de la Cour de justice de l'UE ?", a: "Luxembourg", opts: ["Strasbourg", "Bruxelles", "La Haye"], cat: "villes" },
  { q: "Quelle ville organise le plus grand festival de musiques celtiques ?", a: "Lorient", opts: ["Rennes", "Brest", "Quimper"], cat: "villes" },
  { q: "Dans quelle ville se trouve la cathédrale Saint-Jean-Baptiste ?", a: "Lyon", opts: ["Paris", "Bordeaux", "Nantes"], cat: "villes" },
  { q: "Quelle ville est connue pour son nougat ?", a: "Montélimar", opts: ["Privas", "Valence", "Romans-sur-Isère"], cat: "villes" },
  { q: "Dans quelle ville française a lieu la plus grande foire internationale d'art contemporain (FIAC) ?", a: "Paris", opts: ["Lyon", "Bordeaux", "Nice"], cat: "villes" },
  { q: "Quelle ville est célèbre pour ses montgolfières et le festival « Les Montgolfiades » ?", a: "Annonay", opts: ["Lyon", "Clermont-Ferrand", "Grenoble"], cat: "villes" },
  { q: "Dans quelle ville est installé le siège de l'Agence européenne des droits fondamentaux ?", a: "Vienne (Autriche)", opts: ["Paris", "Strasbourg", "Bruxelles"], cat: "villes" },
  { q: "Quelle ville possède la plus grande zone industrielle portuaire de France ?", a: "Marseille", opts: ["Le Havre", "Dunkerque", "Nantes"], cat: "villes" },
  { q: "Dans quelle ville se trouve le musée Unterlinden ?", a: "Colmar", opts: ["Strasbourg", "Mulhouse", "Sélestat"], cat: "villes" },
  { q: "Quelle ville est connue pour ses chantiers navals et sa flotte militaire ?", a: "Brest", opts: ["Toulon", "Lorient", "Cherbourg"], cat: "villes" },
  { q: "Dans quelle ville se trouve le festival « Vieilles Charrues » ?", a: "Carhaix", opts: ["Rennes", "Brest", "Lorient"], cat: "villes" },
  { q: "Quelle ville normande est célèbre pour ses tapisseries médiévales ?", a: "Bayeux", opts: ["Caen", "Rouen", "Lisieux"], cat: "villes" },

  // ── DÉPARTEMENTS ───────────────────────────────────────────────
  { q: "Dans quel département se trouve le Mont-Saint-Michel ?", a: "Manche", opts: ["Calvados", "Ille-et-Vilaine", "Côtes-d'Armor"], cat: "depts" },
  { q: "Dans quel département se trouve Bordeaux ?", a: "Gironde", opts: ["Dordogne", "Lot-et-Garonne", "Charente"], cat: "depts" },
  { q: "Dans quel département se trouve Strasbourg ?", a: "Bas-Rhin", opts: ["Haut-Rhin", "Moselle", "Meurthe-et-Moselle"], cat: "depts" },
  { q: "Quel est le département le plus grand de France métropolitaine ?", a: "Gironde", opts: ["Landes", "Dordogne", "Côtes-d'Armor"], cat: "depts" },
  { q: "Dans quel département se trouve le Mont Blanc ?", a: "Haute-Savoie", opts: ["Savoie", "Isère", "Hautes-Alpes"], cat: "depts" },
  { q: "Dans quel département se trouve Lourdes ?", a: "Hautes-Pyrénées", opts: ["Ariège", "Pyrénées-Atlantiques", "Haute-Garonne"], cat: "depts" },
  { q: "Dans quel département se trouve Chartres ?", a: "Eure-et-Loir", opts: ["Loir-et-Cher", "Loiret", "Seine-et-Marne"], cat: "depts" },
  { q: "Dans quel département est né Napoléon Bonaparte ?", a: "Corse-du-Sud", opts: ["Haute-Corse", "Var", "Alpes-Maritimes"], cat: "depts" },
  { q: "Dans quel département se trouve Avignon ?", a: "Vaucluse", opts: ["Bouches-du-Rhône", "Gard", "Var"], cat: "depts" },
  { q: "Quel est le numéro du département de Paris ?", a: "75", opts: ["69", "13", "31"], cat: "depts" },
  { q: "Dans quel département se trouvent les mégalithes de Carnac ?", a: "Morbihan", opts: ["Finistère", "Côtes-d'Armor", "Ille-et-Vilaine"], cat: "depts" },
  { q: "Dans quel département se trouve la Dune du Pilat ?", a: "Gironde", opts: ["Charente-Maritime", "Landes", "Dordogne"], cat: "depts" },
  { q: "Dans quel département se trouve Vichy ?", a: "Allier", opts: ["Puy-de-Dôme", "Haute-Loire", "Cantal"], cat: "depts" },
  { q: "Dans quel département se trouve Reims ?", a: "Marne", opts: ["Aisne", "Ardennes", "Aube"], cat: "depts" },
  { q: "Dans quel département se trouve La Rochelle ?", a: "Charente-Maritime", opts: ["Charente", "Vendée", "Deux-Sèvres"], cat: "depts" },
  { q: "Dans quel département se trouve le viaduc de Millau ?", a: "Aveyron", opts: ["Hérault", "Tarn", "Gard"], cat: "depts" },
  { q: "Quel est le numéro du département du Rhône ?", a: "69", opts: ["67", "76", "63"], cat: "depts" },
  { q: "Dans quel département se trouve Annecy ?", a: "Haute-Savoie", opts: ["Savoie", "Ain", "Isère"], cat: "depts" },
  { q: "Quel est le numéro du département du Pas-de-Calais ?", a: "62", opts: ["59", "60", "80"], cat: "depts" },
  { q: "Dans quel département se trouve le château de Chambord ?", a: "Loir-et-Cher", opts: ["Loiret", "Indre-et-Loire", "Sarthe"], cat: "depts" },
  { q: "Dans quel département se trouve Arles ?", a: "Bouches-du-Rhône", opts: ["Gard", "Vaucluse", "Var"], cat: "depts" },
  { q: "Dans quel département se trouve Bayonne ?", a: "Pyrénées-Atlantiques", opts: ["Landes", "Hautes-Pyrénées", "Gers"], cat: "depts" },
  { q: "Dans quel département se trouve Clermont-Ferrand ?", a: "Puy-de-Dôme", opts: ["Allier", "Haute-Loire", "Cantal"], cat: "depts" },
  { q: "Dans quel département se trouve Tours ?", a: "Indre-et-Loire", opts: ["Loir-et-Cher", "Vienne", "Maine-et-Loire"], cat: "depts" },
  { q: "Dans quel département se trouve Montpellier ?", a: "Hérault", opts: ["Gard", "Aude", "Pyrénées-Orientales"], cat: "depts" },
  { q: "Dans quel département se trouve Besançon ?", a: "Doubs", opts: ["Jura", "Haute-Saône", "Ain"], cat: "depts" },
  { q: "Dans quel département se trouve Ajaccio ?", a: "Corse-du-Sud", opts: ["Haute-Corse", "Var", "Alpes-Maritimes"], cat: "depts" },
  { q: "Dans quel département se trouve la forêt de Fontainebleau ?", a: "Seine-et-Marne", opts: ["Essonne", "Yvelines", "Val-de-Marne"], cat: "depts" },
  { q: "Dans quel département se trouve Colmar ?", a: "Haut-Rhin", opts: ["Bas-Rhin", "Moselle", "Meurthe-et-Moselle"], cat: "depts" },
  { q: "Dans quel département se trouve Biarritz ?", a: "Pyrénées-Atlantiques", opts: ["Landes", "Gers", "Hautes-Pyrénées"], cat: "depts" },
  { q: "Dans quel département se trouve Amiens ?", a: "Somme", opts: ["Aisne", "Oise", "Pas-de-Calais"], cat: "depts" },
  { q: "Dans quel département se trouve Cherbourg ?", a: "Manche", opts: ["Calvados", "Orne", "Seine-Maritime"], cat: "depts" },
  { q: "Quel est le numéro du département de la Haute-Garonne ?", a: "31", opts: ["30", "32", "33"], cat: "depts" },
  { q: "Dans quel département se trouve Épernay, capitale du Champagne ?", a: "Marne", opts: ["Aube", "Haute-Marne", "Ardennes"], cat: "depts" },
  { q: "Dans quel département se trouve la pointe du Raz ?", a: "Finistère", opts: ["Morbihan", "Côtes-d'Armor", "Ille-et-Vilaine"], cat: "depts" },

  // ── ROIS & REINES ──────────────────────────────────────────────
  { q: "Quel roi de France fut surnommé « le Roi Soleil » ?", a: "Louis XIV", opts: ["Louis XIII", "Louis XV", "Louis XVI"], cat: "rois" },
  { q: "Quel roi de France fut guillotiné pendant la Révolution ?", a: "Louis XVI", opts: ["Louis XV", "Louis XVIII", "Charles X"], cat: "rois" },
  { q: "Quel roi est considéré comme le premier roi de France ?", a: "Clovis", opts: ["Charlemagne", "Pépin le Bref", "Hugues Capet"], cat: "rois" },
  { q: "Qui fut le premier roi de la dynastie capétienne ?", a: "Hugues Capet", opts: ["Pépin le Bref", "Charles le Chauve", "Lothaire"], cat: "rois" },
  { q: "Quel roi de France fut surnommé « le Bel » ?", a: "Philippe IV", opts: ["Philippe II", "Philippe VI", "Charles IV"], cat: "rois" },
  { q: "Quel roi de France régna le plus longtemps (72 ans) ?", a: "Louis XIV", opts: ["Louis XV", "Henri IV", "François Ier"], cat: "rois" },
  { q: "Quelle reine était l'épouse de Louis XVI ?", a: "Marie-Antoinette", opts: ["Marie-Thérèse", "Catherine de Médicis", "Anne d'Autriche"], cat: "rois" },
  { q: "Qui fut couronné empereur à Rome le 25 décembre 800 ?", a: "Charlemagne", opts: ["Clovis", "Charles le Chauve", "Pépin le Bref"], cat: "rois" },
  { q: "Quel roi de France participa aux croisades et fut canonisé ?", a: "Louis IX", opts: ["Louis VII", "Philippe II", "Louis VIII"], cat: "rois" },
  { q: "Quel roi de France fut assassiné par Ravaillac en 1610 ?", a: "Henri IV", opts: ["Henri III", "Henri II", "Charles IX"], cat: "rois" },
  { q: "Quelle reine régenta la France à la mort d'Henri II ?", a: "Catherine de Médicis", opts: ["Marie de Médicis", "Anne d'Autriche", "Blanche de Castille"], cat: "rois" },
  { q: "Quel roi signa l'Édit de Nantes accordant la liberté de culte ?", a: "Henri IV", opts: ["Louis XIV", "François Ier", "Henri III"], cat: "rois" },
  { q: "Quel roi de France fut surnommé « Auguste » pour ses conquêtes ?", a: "Philippe II", opts: ["Louis IX", "Philippe IV", "Louis VIII"], cat: "rois" },
  { q: "Quelle reine fut décapitée sur ordre d'Élisabeth Ire d'Angleterre ?", a: "Marie Stuart", opts: ["Lady Jane Grey", "Anne Boleyn", "Catherine Howard"], cat: "rois" },
  { q: "Quel roi de France ordonna la nuit de la Saint-Barthélemy ?", a: "Charles IX", opts: ["Henri III", "Henri II", "François II"], cat: "rois" },
  { q: "Quel fut le dernier roi des Français ?", a: "Louis-Philippe Ier", opts: ["Charles X", "Louis XVIII", "Napoléon III"], cat: "rois" },
  { q: "Qui était le père de Louis XIV ?", a: "Louis XIII", opts: ["Henri IV", "Louis XII", "François Ier"], cat: "rois" },
  { q: "Quel roi d'Angleterre eut six femmes successives ?", a: "Henri VIII", opts: ["Henri VII", "Richard III", "Henri IV"], cat: "rois" },
  { q: "Quel roi de France construisit le château de Versailles ?", a: "Louis XIV", opts: ["Louis XIII", "Louis XV", "François Ier"], cat: "rois" },
  { q: "Quel roi de France est associé à la phrase « Paris vaut bien une messe » ?", a: "Henri IV", opts: ["Louis XIV", "François Ier", "Henri III"], cat: "rois" },
  { q: "Sous quel roi de France fut fondée l'Académie française (1635) ?", a: "Louis XIII", opts: ["Louis XIV", "Louis XII", "François Ier"], cat: "rois" },
  { q: "Quel roi de France fut fait prisonnier à la bataille de Pavie en 1525 ?", a: "François Ier", opts: ["Charles VIII", "Louis XII", "Henri II"], cat: "rois" },
  { q: "Quel roi de France fut surnommé « le Vert Galant » ?", a: "Henri IV", opts: ["François Ier", "Henri III", "Louis XIII"], cat: "rois" },
  { q: "Quel roi d'Angleterre fut décapité en 1649 ?", a: "Charles Ier", opts: ["Charles II", "Jacques Ier", "Jacques II"], cat: "rois" },
  { q: "Quelle impératrice gouverna l'Autriche de 1740 à 1780 ?", a: "Marie-Thérèse", opts: ["Marie-Antoinette", "Joséphine", "Catherine II"], cat: "rois" },
  { q: "Catherine la Grande fut impératrice de quel pays ?", a: "Russie", opts: ["Autriche", "Prusse", "France"], cat: "rois" },
  { q: "Quel roi de France reçut le baptême à Reims vers 496 ?", a: "Clovis", opts: ["Charlemagne", "Pépin le Bref", "Dagobert"], cat: "rois" },
  { q: "Quel roi de France mena la septième croisade ?", a: "Louis IX (Saint Louis)", opts: ["Louis VII", "Philippe II", "Charles IV"], cat: "rois" },
  { q: "Quelle fut la reine mère célèbre sous le règne de Louis XIV enfant ?", a: "Anne d'Autriche", opts: ["Catherine de Médicis", "Marie de Médicis", "Marie-Antoinette"], cat: "rois" },
  { q: "Quel roi de France fut le premier de la dynastie des Valois ?", a: "Philippe VI", opts: ["Jean II", "Charles V", "Charles VI"], cat: "rois" },
  { q: "Qui signa la Grande Charte (Magna Carta) en 1215 ?", a: "Jean sans Terre", opts: ["Henri II", "Richard Cœur de Lion", "Henri III"], cat: "rois" },
  { q: "Quel fut le surnom de Louis IX, roi de France ?", a: "Saint Louis", opts: ["le Beau", "le Grand", "le Sage"], cat: "rois" },
  { q: "Dans quelle ville les rois de France étaient-ils couronnés ?", a: "Reims", opts: ["Paris", "Orléans", "Chartres"], cat: "rois" },
  { q: "Quel roi de France fut à l'origine de la construction de Notre-Dame de Paris ?", a: "Louis VII", opts: ["Philippe II", "Louis IX", "François Ier"], cat: "rois" },
  { q: "Quel roi de France signa la révocation de l'Édit de Nantes en 1685 ?", a: "Louis XIV", opts: ["Louis XIII", "Louis XV", "Henri IV"], cat: "rois" },
  { q: "Quelle reine d'Angleterre régna le plus longtemps (70 ans) au XXe et XXIe siècles ?", a: "Élisabeth II", opts: ["Victoria", "Marie Ire", "Anne"], cat: "rois" },
  { q: "Quel roi bâtit la forteresse du Louvre à la fin du XIIe siècle ?", a: "Philippe II Auguste", opts: ["Louis IX", "François Ier", "Charles V"], cat: "rois" },
  { q: "Qui était la mère d'Henri IV de France ?", a: "Jeanne d'Albret", opts: ["Catherine de Médicis", "Marguerite de Valois", "Anne d'Autriche"], cat: "rois" },
  { q: "Quel roi de France lança les grandes ordonnances réformant la justice en 1667 ?", a: "Louis XIV", opts: ["Louis XIII", "Henri IV", "Louis XV"], cat: "rois" },
  { q: "Quel roi porta simultanément les couronnes de France et d'Angleterre ?", a: "Henri VI", opts: ["Henri V", "Édouard III", "Philippe VI"], cat: "rois" },

  // ── PRÉSIDENTS ─────────────────────────────────────────────────
  { q: "Qui fut le premier président de la Ve République française ?", a: "Charles de Gaulle", opts: ["Georges Pompidou", "René Coty", "Vincent Auriol"], cat: "presidents" },
  { q: "Quel président français mit fin à la guerre d'Algérie ?", a: "Charles de Gaulle", opts: ["Georges Pompidou", "Valéry Giscard d'Estaing", "Michel Debré"], cat: "presidents" },
  { q: "Quel président français abolit la peine de mort en 1981 ?", a: "François Mitterrand", opts: ["Valéry Giscard d'Estaing", "Jacques Chirac", "Georges Pompidou"], cat: "presidents" },
  { q: "Quel président français fut réélu en 2002 face à Jean-Marie Le Pen ?", a: "Jacques Chirac", opts: ["Lionel Jospin", "Nicolas Sarkozy", "Laurent Fabius"], cat: "presidents" },
  { q: "Quel président américain abolit l'esclavage ?", a: "Abraham Lincoln", opts: ["Ulysses Grant", "Andrew Johnson", "James Buchanan"], cat: "presidents" },
  { q: "Quel président américain fut assassiné à Dallas en 1963 ?", a: "John F. Kennedy", opts: ["Lyndon Johnson", "Richard Nixon", "Dwight Eisenhower"], cat: "presidents" },
  { q: "Quel fut le premier président des États-Unis ?", a: "George Washington", opts: ["Thomas Jefferson", "John Adams", "Benjamin Franklin"], cat: "presidents" },
  { q: "Quel président américain géra la crise des missiles de Cuba (1962) ?", a: "John F. Kennedy", opts: ["Dwight Eisenhower", "Lyndon Johnson", "Richard Nixon"], cat: "presidents" },
  { q: "Quel président américain créa le programme « New Deal » ?", a: "Franklin D. Roosevelt", opts: ["Harry Truman", "Herbert Hoover", "Woodrow Wilson"], cat: "presidents" },
  { q: "Quel président américain démissionna à cause du scandale du Watergate ?", a: "Richard Nixon", opts: ["Gerald Ford", "Jimmy Carter", "Ronald Reagan"], cat: "presidents" },
  { q: "Quel président américain reçut le prix Nobel de la paix en 2009 ?", a: "Barack Obama", opts: ["Bill Clinton", "Jimmy Carter", "Al Gore"], cat: "presidents" },
  { q: "Quel président français signa le traité de Maastricht (1992) ?", a: "François Mitterrand", opts: ["Jacques Chirac", "Valéry Giscard d'Estaing", "Georges Pompidou"], cat: "presidents" },
  { q: "Quel fut le premier président de la IIe République française ?", a: "Louis-Napoléon Bonaparte", opts: ["Adolphe Thiers", "Louis Blanc", "Lamartine"], cat: "presidents" },
  { q: "Quel président français fit construire la Grande Bibliothèque de France ?", a: "François Mitterrand", opts: ["Jacques Chirac", "Valéry Giscard d'Estaing", "Georges Pompidou"], cat: "presidents" },
  { q: "Quel président français fut à l'origine de la pyramide du Louvre ?", a: "François Mitterrand", opts: ["Georges Pompidou", "Valéry Giscard d'Estaing", "Jacques Chirac"], cat: "presidents" },
  { q: "Quelle était la durée du mandat présidentiel français avant 2000 ?", a: "7 ans", opts: ["5 ans", "4 ans", "6 ans"], cat: "presidents" },
  { q: "En quelle année le mandat présidentiel français fut-il réduit à 5 ans ?", a: "2000", opts: ["1995", "2002", "2007"], cat: "presidents" },
  { q: "Quel président américain décida d'utiliser la bombe atomique sur le Japon ?", a: "Harry Truman", opts: ["Franklin Roosevelt", "Dwight Eisenhower", "Douglas MacArthur"], cat: "presidents" },
  { q: "Quel président américain ouvrit les relations diplomatiques avec la Chine communiste ?", a: "Richard Nixon", opts: ["Jimmy Carter", "Lyndon Johnson", "Gerald Ford"], cat: "presidents" },
  { q: "Quel président français mouru à la suite d'un malaise chez sa maîtresse en 1899 ?", a: "Félix Faure", opts: ["Sadi Carnot", "Paul Deschanel", "Alexandre Millerand"], cat: "presidents" },
  { q: "Quel président français tomba d'un train en pyjama en 1920 ?", a: "Paul Deschanel", opts: ["Félix Faure", "Sadi Carnot", "Gaston Doumergue"], cat: "presidents" },
  { q: "Quel président français fut assassiné à Lyon en 1894 ?", a: "Sadi Carnot", opts: ["Paul Doumer", "Alexandre Millerand", "Raymond Poincaré"], cat: "presidents" },
  { q: "Quel président français fut assassiné en 1932 ?", a: "Paul Doumer", opts: ["Sadi Carnot", "Félix Faure", "Raymond Poincaré"], cat: "presidents" },
  { q: "Quel fut le premier président noir d'Afrique du Sud ?", a: "Nelson Mandela", opts: ["Oliver Tambo", "Thabo Mbeki", "Steve Biko"], cat: "presidents" },
  { q: "Quel chancelier allemand réunifié l'Allemagne en 1990 ?", a: "Helmut Kohl", opts: ["Willy Brandt", "Gerhard Schröder", "Konrad Adenauer"], cat: "presidents" },
  { q: "Quel est le prénom de l'ancien président de Gaulle ?", a: "Charles", opts: ["Philippe", "Jean", "Georges"], cat: "presidents" },
  { q: "En quelle année de Gaulle quitta-t-il le pouvoir ?", a: "1969", opts: ["1968", "1970", "1962"], cat: "presidents" },
  { q: "Quel président français était au pouvoir lors de la chute du mur de Berlin (1989) ?", a: "François Mitterrand", opts: ["Jacques Chirac", "Valéry Giscard d'Estaing", "Michel Rocard"], cat: "presidents" },
  { q: "Quel fut le premier président de la IIIe République française ?", a: "Adolphe Thiers", opts: ["Mac Mahon", "Jules Grévy", "Jules Ferry"], cat: "presidents" },
  { q: "Sous quel président la Tour Eiffel fut-elle construite (1889) ?", a: "Sadi Carnot", opts: ["Jules Grévy", "Félix Faure", "Raymond Poincaré"], cat: "presidents" },
  { q: "Quel président cohabita avec le Premier ministre Lionel Jospin de 1997 à 2002 ?", a: "Jacques Chirac", opts: ["François Mitterrand", "Valéry Giscard d'Estaing", "Nicolas Sarkozy"], cat: "presidents" },
  { q: "En quelle année Emmanuel Macron fut-il élu président pour la première fois ?", a: "2017", opts: ["2012", "2022", "2007"], cat: "presidents" },
  { q: "Quel président américain introduisit le plan Marshall pour reconstruire l'Europe ?", a: "Harry Truman", opts: ["Dwight Eisenhower", "Franklin Roosevelt", "George Marshall"], cat: "presidents" },
  { q: "Quelle personnalité fut le premier secrétaire général de l'ONU (1945) ?", a: "Trygve Lie", opts: ["Dag Hammarskjöld", "U Thant", "Kurt Waldheim"], cat: "presidents" },
  { q: "Quel président américain créa la NASA en 1958 ?", a: "Dwight Eisenhower", opts: ["John F. Kennedy", "Harry Truman", "Lyndon Johnson"], cat: "presidents" },
  { q: "Quel président français instaura les régions administratives en 1982 ?", a: "François Mitterrand", opts: ["Charles de Gaulle", "Georges Pompidou", "Valéry Giscard d'Estaing"], cat: "presidents" },
  { q: "Qui prononça la célèbre phrase « Ask not what your country can do for you… » ?", a: "John F. Kennedy", opts: ["Abraham Lincoln", "Franklin Roosevelt", "Woodrow Wilson"], cat: "presidents" },
  { q: "Quel président américain signa la loi sur les droits civiques en 1964 ?", a: "Lyndon B. Johnson", opts: ["John F. Kennedy", "Richard Nixon", "Dwight Eisenhower"], cat: "presidents" },
  { q: "Quel président français décida la nationalisation des grandes banques en 1981 ?", a: "François Mitterrand", opts: ["Georges Pompidou", "Jacques Chirac", "Valéry Giscard d'Estaing"], cat: "presidents" },
  { q: "Quel premier ministre britannique fut la première femme à ce poste ?", a: "Margaret Thatcher", opts: ["Theresa May", "Tony Blair", "Gordon Brown"], cat: "presidents" },

  // ── GRANDES GUERRES ────────────────────────────────────────────
  { q: "En quelle année débuta la Première Guerre mondiale ?", a: "1914", opts: ["1912", "1916", "1910"], cat: "guerres" },
  { q: "En quelle année se termina la Seconde Guerre mondiale ?", a: "1945", opts: ["1943", "1944", "1946"], cat: "guerres" },
  { q: "Quel événement déclencha la Première Guerre mondiale ?", a: "L'assassinat de l'archiduc François-Ferdinand", opts: ["L'invasion de la Belgique", "La déclaration de guerre de la France", "La mobilisation allemande"], cat: "guerres" },
  { q: "Où eut lieu le débarquement allié du 6 juin 1944 ?", a: "Normandie", opts: ["Provence", "Bretagne", "Picardie"], cat: "guerres" },
  { q: "Quel traité mit fin à la Première Guerre mondiale ?", a: "Traité de Versailles", opts: ["Traité de Paris", "Traité de Vienne", "Traité de Berlin"], cat: "guerres" },
  { q: "Quelle bataille de 1916 fut la plus meurtrière sur le front français ?", a: "Bataille de Verdun", opts: ["Bataille de la Marne", "Bataille de la Somme", "Bataille d'Ypres"], cat: "guerres" },
  { q: "Quel pays bombarda la base américaine de Pearl Harbor en 1941 ?", a: "Japon", opts: ["Allemagne", "Italie", "URSS"], cat: "guerres" },
  { q: "En quelle année la France capitula-t-elle face à l'Allemagne nazie ?", a: "1940", opts: ["1939", "1941", "1942"], cat: "guerres" },
  { q: "Quelle ville japonaise reçut la première bombe atomique ?", a: "Hiroshima", opts: ["Nagasaki", "Tokyo", "Osaka"], cat: "guerres" },
  { q: "Quel général français lança l'appel du 18 juin 1940 ?", a: "Charles de Gaulle", opts: ["Philippe Pétain", "Henri Giraud", "Maxime Weygand"], cat: "guerres" },
  { q: "Quelle guerre se déroula sur la péninsule coréenne de 1950 à 1953 ?", a: "Guerre de Corée", opts: ["Guerre du Vietnam", "Guerre d'Indochine", "Guerre sino-japonaise"], cat: "guerres" },
  { q: "La France mena la guerre d'Indochine de 1946 à quelle année ?", a: "1954", opts: ["1950", "1956", "1960"], cat: "guerres" },
  { q: "Quelle bataille mit fin aux guerres napoléoniennes en 1815 ?", a: "Waterloo", opts: ["Austerlitz", "Leipzig", "Wagram"], cat: "guerres" },
  { q: "Combien d'années dura réellement la « guerre de Cent Ans » ?", a: "116 ans", opts: ["100 ans", "75 ans", "120 ans"], cat: "guerres" },
  { q: "Contre quel pays la France mena-t-elle la guerre de 1870-1871 ?", a: "Prusse", opts: ["Autriche", "Italie", "Russie"], cat: "guerres" },
  { q: "En quelle année se termina la guerre de Cent Ans ?", a: "1453", opts: ["1415", "1429", "1461"], cat: "guerres" },
  { q: "Quelle bataille marqua le tournant de la guerre à l'Est en 1942-1943 ?", a: "Stalingrad", opts: ["Moscou", "Koursk", "Leningrad"], cat: "guerres" },
  { q: "Quelle alliance militaire occidentale fut créée en 1949 ?", a: "OTAN", opts: ["Pacte de Varsovie", "ONU", "CECA"], cat: "guerres" },
  { q: "Quel pays envahit la Pologne le 1er septembre 1939, déclenchant la Seconde Guerre mondiale ?", a: "Allemagne nazie", opts: ["URSS", "Italie", "Hongrie"], cat: "guerres" },
  { q: "Comment s'appelait l'opération du débarquement allié en Normandie ?", a: "Opération Overlord", opts: ["Opération Torch", "Opération Market Garden", "Opération Neptune"], cat: "guerres" },
  { q: "Quel général américain commanda les forces alliées lors du débarquement de 1944 ?", a: "Dwight Eisenhower", opts: ["George Patton", "Bernard Montgomery", "Douglas MacArthur"], cat: "guerres" },
  { q: "En quelle année fut signé l'armistice mettant fin à la Première Guerre mondiale ?", a: "1918", opts: ["1916", "1917", "1919"], cat: "guerres" },
  { q: "Quel traité mit fin à la guerre de Trente Ans en 1648 ?", a: "Traité de Westphalie", opts: ["Traité d'Utrecht", "Traité de Vienne", "Traité d'Augsbourg"], cat: "guerres" },
  { q: "Quel célèbre tableau de Picasso représente les horreurs de la guerre civile espagnole ?", a: "Guernica", opts: ["Les Demoiselles d'Avignon", "La Colombe", "Le Massacre en Corée"], cat: "guerres" },
  { q: "En quelle année la France colonisa-t-elle l'Algérie ?", a: "1830", opts: ["1848", "1881", "1912"], cat: "guerres" },
  { q: "Quel pays utilisa en premier les chars d'assaut au combat (1916) ?", a: "Grande-Bretagne", opts: ["France", "Allemagne", "États-Unis"], cat: "guerres" },
  { q: "La défaite française de Dien Bien Phu (1954) mit fin à la guerre d'... ?", a: "Indochine", opts: ["Corée", "Algérie", "Vietnam"], cat: "guerres" },
  { q: "En quelle année tomba le mur de Berlin ?", a: "1989", opts: ["1990", "1991", "1985"], cat: "guerres" },
  { q: "Quel pays rejoignit les Alliés après l'attaque de Pearl Harbor ?", a: "États-Unis", opts: ["Canada", "Mexique", "Brésil"], cat: "guerres" },
  { q: "En quelle année débuta la guerre du Golfe (opération Tempête du Désert) ?", a: "1991", opts: ["1990", "1992", "1989"], cat: "guerres" },
  { q: "Quelle guerre opposa en 1870 la France à la Prusse et se termina par la perte de l'Alsace-Lorraine ?", a: "Guerre franco-prussienne", opts: ["Guerre de Crimée", "Guerre des Boers", "Guerre d'Italie"], cat: "guerres" },
  { q: "Quel accord créa la ligne directe téléphonique entre Washington et Moscou après la crise de Cuba ?", a: "Téléphone rouge (Hotline)", opts: ["Traité de Moscou", "Accords SALT", "Accord de Genève"], cat: "guerres" },
  { q: "Où fut signé l'armistice du 11 novembre 1918 ?", a: "Dans un wagon à Rethondes (forêt de Compiègne)", opts: ["À Paris", "À Versailles", "À Berlin"], cat: "guerres" },
  { q: "Quelle bataille navale de 1805 mit fin aux ambitions maritimes de Napoléon ?", a: "Trafalgar", opts: ["Aboukir", "Le Nil", "Copenhague"], cat: "guerres" },
  { q: "Quel pays fut divisé en deux à la fin de la Seconde Guerre mondiale, récréant une frontière au 38e parallèle ?", a: "Corée", opts: ["Vietnam", "Allemagne", "Chine"], cat: "guerres" },
  { q: "Quel maréchal devint chef du gouvernement de Vichy en 1940 ?", a: "Philippe Pétain", opts: ["Ferdinand Foch", "Maxime Weygand", "Alphonse Juin"], cat: "guerres" },
  { q: "En quelle année commença la guerre d'Algérie ?", a: "1954", opts: ["1945", "1958", "1962"], cat: "guerres" },
  { q: "Quel est le nom du plan allié de débarquement en Sicile (1943) ?", a: "Opération Husky", opts: ["Opération Torch", "Opération Cobra", "Opération Barbarossa"], cat: "guerres" },
  { q: "Comment s'appelait l'offensive allemande qui envahit l'URSS en juin 1941 ?", a: "Opération Barbarossa", opts: ["Opération Blitzkrieg", "Opération Fall Gelb", "Opération Citadelle"], cat: "guerres" },
  { q: "Quelle fut la durée de la Première Guerre mondiale ?", a: "4 ans (1914-1918)", opts: ["3 ans", "5 ans", "6 ans"], cat: "guerres" },
];

export function randomCultureQ(cat?: CultureCat): CultureQ {
  const pool = cat ? CULTURE.filter(q => q.cat === cat) : CULTURE;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function shuffleOptions(q: CultureQ): string[] {
  const all = [q.a, ...q.opts];
  for (let i = all.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [all[i], all[j]] = [all[j], all[i]];
  }
  return all;
}
